- name: Install psycopg2 (Python PostgreSQL adapter)
  pip:
    name: psycopg2-binary 
    state: present

- name: GPG key PostgreSQL
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Add PostgreSQL repo
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main"
    state: present
    filename: 'pgdg'

- name: Update cahce
  apt:
    update_cache: yes

- name: Install PostgreSQL
  apt:
    name: postgresql
    state: latest

- name: Start and enable PostgreSQL 
  service:
    name: "postgresql"
    state: started
    enabled: true

- name: Get PostgreSQL version
  shell: "psql --version | grep -oP '\\d+' | head -n1"
  register: pg_version
  changed_when: false

- name: Create db 
  community.postgresql.postgresql_db:
    name: db
    state: present  
  become: true
  become_user: postgres

- name: Add student access 
  lineinfile:
    path: /etc/postgresql/{{ pg_version.stdout }}/main/pg_hba.conf
    line: "host    all             student         {{ student_ip }}/32        md5"
    state: present

- name: Enable connections 
  lineinfile:
    path: /etc/postgresql/{{ pg_version.stdout }}/main/postgresql.conf
    line: "listen_addresses = '*'"
    state: present

- name: Restart PostgreSQL
  service:
    name: postgresql
    state: restarted
  
- name: Test
  community.postgresql.postgresql_query:
    query: "SELECT 1 FROM pg_database WHERE datname = 'db'"
  register: db_exists
  become: true
  become_user: postgres
  changed_when: false
